[package]
name = "detect-virt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse_int = "0.5.0"
procfs = "0.9.1"
raw-cpuid = "10.2.0"
